version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cashflow
      POSTGRES_USER: cashflow
      POSTGRES_PASSWORD: cashflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn cashflow.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    depends_on:
      - web

volumes:
  postgres_data: 